# Generated by Django 4.2.20 on 2025-04-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_adhaar_number_profile_dob_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Patient',
        ),
    ]
