# Generated by Django 4.2.20 on 2025-04-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_allergies_profile_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='patient_id',
            field=models.CharField(editable=False, max_length=15, null=True, unique=True),
        ),
    ]
