# Generated by Django 4.2.20 on 2025-04-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_update_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_id_display',
            field=models.CharField(editable=False, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id_display',
            field=models.CharField(editable=False, max_length=15, null=True),
        ),
    ]
