# Generated by Django 4.2.20 on 2025-04-13 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_appointment_doctor_id_display_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('consult_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id_display', models.CharField(blank=True, editable=False, max_length=15, null=True)),
                ('doctor_id_display', models.CharField(blank=True, editable=False, max_length=15, null=True)),
                ('consultation_type', models.CharField(choices=[('Chat', 'Chat'), ('Audio call', 'Audio call'), ('Video Call', 'Video Call')], max_length=20)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('past_surgeries', models.TextField(blank=True, null=True)),
                ('previous_medications', models.TextField(blank=True, null=True)),
                ('consultation_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
            options={
                'db_table': 'Consultancy',
                'managed': True,
            },
        ),
    ]
