# Generated by Django 5.2 on 2025-04-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_create_consultancy_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('ambulance_assign_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('ambulance_assigned', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Arrived', 'Arrived'), ('Completed', 'Completed')], max_length=20)),
                ('arrival_time_in_hospital', models.DateTimeField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_contact_num', models.CharField(blank=True, max_length=15, null=True)),
                ('legal_issues_reported', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('legal_case_number', models.CharField(blank=True, max_length=20, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
    ]
