# Generated by Django 4.2.20 on 2025-04-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_emergency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancy',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='consultancy',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Consultancy',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Emergency',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
